# Generated by Django 2.2.3 on 2019-07-10 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15)),
                ('sid_1', models.CharField(blank=True, max_length=18)),
                ('sid_2', models.CharField(blank=True, max_length=18)),
                ('rn', models.CharField(blank=True, max_length=12)),
                ('version', models.CharField(blank=True, max_length=19)),
                ('enable_SearchMode', models.BooleanField(blank=True)),
                ('launch_period', models.IntegerField(blank=True)),
                ('time_GPS_search', models.IntegerField(blank=True)),
                ('time_GSM_registration', models.IntegerField(blank=True)),
                ('send_SMS_SearchMode', models.BooleanField(blank=True)),
                ('enable_acс', models.BooleanField(blank=True)),
                ('send_SMS_MoveAcc', models.BooleanField(blank=True)),
                ('send_data_Email', models.BooleanField(blank=True)),
                ('send_status_30days', models.BooleanField(blank=True)),
                ('date_device_registration', models.DateField()),
                ('battery_level', models.FloatField(blank=True)),
                ('date_to_end', models.IntegerField(blank=True)),
                ('date_last_message', models.DateField(blank=True)),
                ('date_next_message', models.DateField(blank=True)),
                ('temperature', models.FloatField(blank=True)),
                ('last_message_sim', models.CharField(blank=True, max_length=1)),
                ('GPS_last_HDOP', models.CharField(blank=True, max_length=4)),
                ('GPS_time_UTC', models.CharField(blank=True, max_length=10)),
                ('GPS_status', models.CharField(blank=True, max_length=1)),
                ('GPS_laitude', models.CharField(blank=True, max_length=9)),
                ('GPS_n_s', models.CharField(blank=True, max_length=1)),
                ('GPS_longitude', models.CharField(blank=True, max_length=10)),
                ('GPS_e_w', models.CharField(blank=True, max_length=1)),
                ('GPS_speed', models.IntegerField(blank=True)),
                ('GPS_course', models.CharField(blank=True, max_length=8)),
                ('GPS_date', models.CharField(blank=True, max_length=6)),
                ('GSM_MCC', models.CharField(blank=True, max_length=3)),
                ('GSM_MNC', models.CharField(blank=True, max_length=3)),
                ('GSM_LAC', models.CharField(blank=True, max_length=8)),
                ('GSM_cell', models.CharField(blank=True, max_length=8)),
                ('GSM_dBm', models.IntegerField(blank=True)),
                ('motion', models.BooleanField(blank=True)),
                ('motion_T', models.IntegerField(blank=True)),
                ('motion_TS', models.IntegerField(blank=True)),
                ('balance_info', models.CharField(blank=True, max_length=162)),
                ('data_r', models.CharField(blank=True, max_length=10)),
                ('data_t', models.CharField(blank=True, max_length=8)),
                ('data_p', models.CharField(blank=True, max_length=8)),
                ('data_s', models.CharField(blank=True, max_length=8)),
                ('data_c', models.CharField(blank=True, max_length=8)),
                ('data_o', models.CharField(blank=True, max_length=8)),
                ('data_d', models.CharField(blank=True, max_length=8)),
                ('data_g', models.CharField(blank=True, max_length=8)),
                ('data_a', models.CharField(blank=True, max_length=8)),
                ('data_n', models.CharField(blank=True, max_length=8)),
                ('data_z', models.CharField(blank=True, max_length=8)),
                ('data_m', models.CharField(blank=True, max_length=8)),
                ('data_button', models.CharField(blank=True, max_length=1)),
                ('data_F', models.CharField(blank=True, max_length=2)),
                ('data_time_GPS', models.CharField(blank=True, max_length=13)),
                ('data_time_GSM', models.CharField(blank=True, max_length=13)),
                ('SMS_code', models.CharField(blank=True, max_length=1)),
                ('SMS_text', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
