# Generated by Django 2.2.3 on 2019-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20190710_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='launch_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
