# Generated by Django 2.2.3 on 2019-07-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_auto_20190710_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_device_registration',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_last_message',
            field=models.DateField(auto_now=True),
        ),
    ]
