# Generated by Django 2.2.3 on 2019-07-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_auto_20190710_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_next_message',
            field=models.DateField(null=True),
        ),
    ]
