# Generated by Django 2.2.3 on 2019-07-10 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_auto_20190710_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_from_FM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=19)),
                ('type_con', models.CharField(max_length=1)),
                ('sid', models.CharField(max_length=18)),
                ('p_roaming', models.CharField(max_length=1)),
                ('ops', models.CharField(max_length=7)),
                ('data', models.TextField(blank=True)),
                ('cs', models.CharField(max_length=3)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('imei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.Device')),
            ],
            options={
                'ordering': ['-date_pub'],
            },
        ),
    ]
