# Generated by Django 2.2.3 on 2019-07-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_auto_20190711_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='time_GPS_search',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='time_GSM_registration',
            field=models.IntegerField(default=30),
        ),
    ]
