# Generated by Django 2.2.3 on 2019-07-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0011_auto_20190711_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='GSM_LAC',
        ),
        migrations.RemoveField(
            model_name='device',
            name='GSM_MCC',
        ),
        migrations.RemoveField(
            model_name='device',
            name='GSM_MNC',
        ),
        migrations.RemoveField(
            model_name='device',
            name='GSM_cell',
        ),
        migrations.RemoveField(
            model_name='device',
            name='GSM_dBm',
        ),
        migrations.AddField(
            model_name='device',
            name='GSM_data',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='device',
            name='temperature',
            field=models.CharField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
    ]
