# Generated by Django 2.2.3 on 2019-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0012_auto_20190712_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='data_a',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_button',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_c',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_d',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_g',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_m',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_n',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_o',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_p',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_r',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_s',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_t',
        ),
        migrations.RemoveField(
            model_name='device',
            name='data_z',
        ),
        migrations.AddField(
            model_name='device',
            name='log_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
