# Generated by Django 2.2.3 on 2019-07-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0013_auto_20190712_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_param',
            field=models.TextField(blank=True, null=True),
        ),
    ]
