# Generated by Django 2.2.3 on 2019-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_device_device_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='GPS_laitude',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='GPS_longitude',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
