# Generated by Django 2.2.3 on 2019-07-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0016_auto_20190716_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='GPS_laitude',
            new_name='GPS_latitude',
        ),
    ]
