# Generated by Django 2.2.3 on 2019-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0017_auto_20190724_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='GSM_latitude',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='device',
            name='GSM_longitude',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
