# Generated by Django 2.2.3 on 2019-07-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0018_auto_20190724_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='GSM_data',
        ),
    ]
